name: Go Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install dependencies
        run: go get -d ./...

      - name: Run Tests
        run: go test -v ./...

      - name: Run Staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: 2022.1.3

      - name: Install golangci-lint
        run: go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.0

      - name: Run Linter
        run: golangci-lint run
